src/SportsStore.prj/SportsStore.WebService/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.WebService.Models;

namespace SportsStore.WebService.Components;

public class CartSummaryViewComponent : ViewComponent
{
	private readonly Cart _cart;

	public CartSummaryViewComponent(Cart cart)
	{
		_cart = cart ?? throw new System.ArgumentNullException(nameof(cart));
	}

	public IViewComponentResult Invoke() => View(_cart);
}

src/SportsStore.prj/SportsStore.WebService/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.WebService.Database;
using System.Linq;

namespace SportsStore.WebService.Components;

public class NavigationMenuViewComponent : ViewComponent
{
	private readonly IProductRepository _productRepository;

	public NavigationMenuViewComponent(IProductRepository productRepository)
	{
		_productRepository = productRepository ?? throw new System.ArgumentNullException(nameof(productRepository));
	}

	public IViewComponentResult Invoke()
	{
		var products = _productRepository.Products.Select(x => x.Category).Distinct().OrderBy(x => x);
		ViewBag.SelectedCategory = RouteData?.Values["category"];
		return View(products);
	}

}

src/SportsStore.prj/SportsStore.WebService/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using SportsStore.WebService.Database;
using SportsStore.WebService.Models;
using System.Linq;
using SportsStore.WebService.Infrastructure;
using SportsStore.WebService.Models.ViewModels;

namespace SportsStore.WebService.Controllers;
public class CartController : Controller
{
	private readonly IProductRepository _productRepository;
	private readonly Cart _cart;

	public CartController(IProductRepository productRepository, Cart cart)
	{
		_productRepository = productRepository ?? throw new System.ArgumentNullException(nameof(productRepository));
		_cart              = cart ?? throw new System.ArgumentNullException(nameof(cart));
	}

	public RedirectToActionResult AddToCart(int productId, string returnUrl)
	{
		var product = _productRepository.Products.FirstOrDefault(p => p.Id == productId);

		if(product != null) _cart.AddItem(product, 1);

		return RedirectToAction("Index", new { returnUrl });
	}

	public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
	{
		var product = _productRepository.Products.FirstOrDefault(p => p.Id == productId);

		if(product != null) _cart.RemoveLine(product);

		return RedirectToAction("Index", new { returnUrl });
	}

	public ViewResult Index(string returnUrl)
	{
		var cartIndex = new CartIndexViewModel()
		{
			Cart      = _cart,
			ReturnUrl = returnUrl
		};

		return View(cartIndex);
	}
}

src/SportsStore.prj/SportsStore.WebService/Views/Shared/ProductSummary.cshtml
@using SportsStore.WebService.Models
@using SportsStore.WebService.Infrastructure
@model Product


<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
        </h4>
        <div style="float:right;margin-right:1%">@Model.Price.ToString("c")</div>
        <div class="card-text p-1">Description: @Model.Description</div>
        <div class="card-text p-1">Category: @Model.Category</div>
    </div>
    <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" name="productId" value="@Model.Id" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cards
            </button>
        </span>
    </form>
</div>

src/SportsStore.prj/SportsStore.WebService/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <title>@ViewBag.Title</title>
</head>
<body class="m-1 p-1">
    <div>
        <div class="bg-info p-2 row">
            <div class="col">
                <h4>@ViewBag.Title</h4>
            </div>
            <div class="col-2">
                <a class="btn btn-sm btn-primary" asp-action="Logout" asp-controller="Account">
                    LogOut
                </a>
            </div>

        </div>
        @if(TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

src/SportsStore.prj/SportsStore.WebService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/mainStyle.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/*.css" rel="stylesheet" />
    <title>SportsStore</title>
</head>
<body>
    <header>
        <h1>SPORTS STORE</h1>
        <ul class="nav">
            <li><a class="btn btn-block btn-secondary" style="height: 100%;" href="#">ДОБАВИТЬ ТОВАР</a></li>
            <li><a class="btn btn-block btn-secondary" style="height: 100%;" href="#">УДАЛИТЬ ТОВАР</a></li>
            <li><a class="btn btn-block btn-secondary" style="height: 100%;" href="#">СПИСОК ТОВАРА</a></li>
            <li><a class="btn btn-block btn-secondary" style="height: 100%;" href="#">ВХОД ВЫХОД</a></li>
            <li>
                @await Component.InvokeAsync("CartSummary")
            </li>

        </ul>
    </header>
    <main>
        <div class="leftMenu">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="content">
            @RenderBody()
        </div>
    </main>
    <footer>
        <h1>Данный проект - проект по книжке asp net core Фриманова, "</h1>J
    </footer>
</body>
</html>